<!-- Required Js -->
<script src="{{ asset('assets/js/vendor-all.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/ripple.js') }}"></script>
<script src="{{ asset('assets/js/pcoded.min.js') }}"></script>
<script src="{{ asset('assets/js/notification/notification.js') }}"></script>

<!-- datatable Js -->
<script src="{{ asset('assets/js/plugins/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/sweetalert.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/helper/helper.js') }}"></script>
<script src="{{ asset('assets/js/pages/roleNames/roleNames.js') }}"></script>
<script src="{{ asset('assets/js/pages/roles/roles.js') }}"></script>
<script src="{{ asset('assets/js/pages/admin/admin.js') }}"></script>
<script src="{{ asset('assets/js/pages/department/department.js') }}"></script>
<script src="{{ asset('assets/js/pages/semester/semester.js') }}"></script>
<script src="{{ asset('assets/js/pages/educationLevel/educationLevel.js') }}"></script>
<script src="{{ asset('assets/js/pages/educationType/educationType.js') }}"></script>
<script src="{{ asset('assets/js/pages/stage/stage.js') }}"></script>
<script src="{{ asset('assets/js/pages/year/year.js') }}"></script>
<script src="{{ asset('assets/js/pages/studyStatus/studyStatus.js') }}"></script>
<script src="{{ asset('assets/js/pages/studyType/studyType.js') }}"></script>